
package ru.ohapegor.logFinder.userInterface.services.webClients.soapClient;

import ru.ohapegor.logFinder.entities.SearchInfo;
import ru.ohapegor.logFinder.entities.SearchInfoResult;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchLogSOAP", targetNamespace = "http://soap.web_services.services.logFinder.ohapegor.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchLogSOAPClient {


    /**
     * 
     * @param arg0
     * @return
     *     returns logFinderSOAPClient.SearchInfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logSearch", targetNamespace = "http://soap.web_services.services.logFinder.ohapegor.ru/", className = "logFinderSOAPClient.LogSearchSOAP")
    @ResponseWrapper(localName = "logSearchResponse", targetNamespace = "http://soap.web_services.services.logFinder.ohapegor.ru/", className = "logFinderSOAPClient.LogSearchResponseClient")
    @Action(input = "http://soap.web_services.services.logFinder.ohapegor.ru/SearchLogSOAP/logSearchRequest", output = "http://soap.web_services.services.logFinder.ohapegor.ru/SearchLogSOAP/logSearchResponse")
    public SearchInfoResult logSearch(
            @WebParam(name = "arg0", targetNamespace = "")
                    SearchInfo arg0);


}
